export const SIGNED_IN = 'SIGNED_IN';
export const SET_GOALS = 'SET_GOALS';
export const SET_COMPLETED = 'SET_COMPLETED';

export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';
